# CS460 Algorithms and Their Analysis
## Programming Assignment 4: Dynamic programming algorithms -- Matrix chain multiplication

**Author:** Yang Xu, Assistant Professor of Computer Science, San Diego State University

**Total points: 10**

## Task 1: Implement Matrix-chain-order procudure
**Points: 4**

Implement the `matrix_chain_order()` function following the pseudo code.

- The `m` and `s` 2D arrays are represented by list of lists
- Note that when using `range()` to set the range of for loop, the upper bound is exclusive.
- the indices of solution matrix `s` start with 2 in the pseudo code, but here they start with 0. This means you need to adjust the indices when accessing the $i$th row and $j$th column of `s`.

In [1]:
import numpy as np 

def matrix_chain_order(p):
    n = len(p)-1
    ### START YOUR CODE ###
    m = [[0 for _ in range(n+1)] for _ in range(n+1)]
    s = [[0 for _ in range(n)] for _ in range(n)]
    ### END YOUR CODE ###

    ### START YOUR CODE ###
    for l in range(2, n+1): # Specify the range
        for i in range(1, n-l+2): # Specify the range
            j = i + l - 1 # Initialize
            m[i][j] = float('inf')
            for k in range(i, j): # Specify the range
                q = m[i][k] + m[k+1][j] + p[i-1]*p[k]*p[j]
                if q < m[i][j]:
                    m[i][j] = q # Update m
                    s[i-1][j-1] = k # Update s
    ### END YOUR CODE ###

    return m, s

In [2]:
# Do not change the test code here
p = [30, 35, 15, 5, 10]
m, s = matrix_chain_order(p)
print(np.array(m))
print(np.array(s))

[[    0     0     0     0     0]
 [    0     0 15750  7875  9375]
 [    0     0     0  2625  4375]
 [    0     0     0     0   750]
 [    0     0     0     0     0]]
[[0 1 1 3]
 [0 0 2 3]
 [0 0 0 3]
 [0 0 0 0]]


**Expected output**:

[[    0     0     0     0     0]\
 [    0     0 15750  7875  9375]\
 [    0     0     0  2625  4375]\
 [    0     0     0     0   750]\
 [    0     0     0     0     0]]

[[0 1 1 3]\
 [0 0 2 3]\
 [0 0 0 3]\
 [0 0 0 0]]

## Task 2: Implement print-optimal-parens procedure
**Points: 2**

Implement the `print_optimal_parens()` function following the pseudo code.

In [3]:
def print_optimal_parens(s, i, j):
    if i == j:
        print("A" + str(i), end=" ")
    else:
        print("(", end=" ")
        ### START YOUR CODE ###
        # Specify two recursive calls correctly
        print_optimal_parens(s, i, s[i-1][j-1])
        print_optimal_parens(s, s[i-1][j-1] + 1, j)
        ### END YOUR CODE ###
        print(")", end=" ")

In [4]:
# Do not change the test code here
p = [30, 35, 15, 5, 10]
m, s = matrix_chain_order(p)
print_optimal_parens(s, 1, len(p)-1)

( ( A1 ( A2 A3 ) ) A4 ) 

**Expected output**:

( ( A1 ( A2 A3 ) ) A4 )

---

## Task 3: Implement the top-down solution
**Points: 4**

Implement the `memoized_matrix_chain()` and `lookup_chain()` functions following the pseudo code.

In [5]:
def memoized_matrix_chain(p):
    n = len(p) - 1
    ### START YOUR CODE ###
    m = [[0 for _ in range(n+1)] for _ in range(n+1)] # Initialize m to the correct size
    for i in range(n): # Specxify the range
        for j in range(i, n+1): # Specxify the range
            m[i][j] = float('inf')

    return lookup_chain(m, p, 1, n) # Call lookup_chain correctly
    ### END YOUR CODE ###

def lookup_chain(m, p, i, j):
    ### START YOUR CODE ###
    if m[i][j] < float('inf'):
        return m[i][j] # Return the correct value
    if i == j:
        m[i][j] = 0 # Update m
    else:
        for k in range(i, j): # Specify the range
            q = lookup_chain(m, p, i, k) + lookup_chain(m, p, k+1, j) + p[i-1]*p[k]*p[j] # Compute q
            if q < m[i][j]:
                m[i][j] = q # Update m

    return m[i][j] # Return the correct value
    ### END YOUR CODE ###

In [6]:
# Do not change the test code here
p = [30, 35, 15, 5, 10]
print(memoized_matrix_chain(p))

9375


**Expected output**

9375